---
- name: upgrade all packages
  apt: upgrade=full

- name: create Group gogroup
  group: name=gogroup state=present
  
- name: create User
  user: name=gouser group=gogroup shell=/bin/bash 

- name: Create Directory Previous Transferring Application
  file: path=/opt/goapp/ state=directory mode=0755

- name: Copy Application to Remote Servers
  copy: src=opt/goapp/web_app dest=/opt/goapp/web_app owner=gouser group=gogroup mode=755

- name: Copy web_app_init.sh to init.d  
  copy: src=opt/goapp/web_app_init.sh  dest=/etc/init.d/web_app_init.sh owner=gouser group=gogroup mode=755

- name: Start Application
  shell: "update-rc.d web_app_init.sh defaults;/etc/init.d/web_app_init.sh start"
  args:
   executable: "/bin/bash"
